/**
 * İçerik anahtarlarının Türkçe karşılıkları.
 *
 * Panelde alan adı olarak "title" değil "Başlık" yazsın diye. Sözlükte
 * olmayan anahtar olduğu gibi gösterilir — panel yine de çalışır.
 */

/** Tek bir metin alanının etiketi (yolun son parçasına göre) */
export const FIELD_LABELS: Record<string, string> = {
  title: "Başlık",
  subtitle: "Alt başlık",
  sub: "Alt başlık",
  text: "Metin",
  body: "Metin",
  desc: "Açıklama",
  description: "Açıklama",
  lead: "Giriş metni",
  excerpt: "Özet",
  kicker: "Üst başlık",
  eyebrow: "Üst başlık",
  label: "Etiket",
  name: "Ad",
  tagline: "Slogan",
  summary: "Özet",
  channel: "Satış kanalı bağlantı metni",
  cta: "Buton yazısı",
  ctaTitle: "Kapanış başlığı",
  ctaButton: "Buton yazısı",
  button: "Buton yazısı",
  note: "Not",
  hint: "İpucu",
  alt: "Görsel açıklaması (alt)",
  source: "Kaynak",
  n: "Değer",
  l: "Etiket",
  k: "Özellik",
  v: "Değer",
  inch: "İnç",
  days: "Gün aralığı",
  readingTime: "Okuma süresi",
  soon: "Yakında etiketi",
  verified: "Doğrulama rozeti",
  all: "Tümünü gör bağlantısı",
  view: "Kart buton yazısı",
  prev: "Önceki (erişilebilirlik)",
  next: "Sonraki (erişilebilirlik)",
  roleDescription: "Ekran okuyucu açıklaması",
  menuAria: "Menü (erişilebilirlik)",
  brandsLabel: "Markalar menüsü",
  about: "Hakkımızda menüsü",
  contact: "İletişim menüsü",
  unit: "Birim",
  legendHome: "Harita göstergesi — merkez",
  legendMarket: "Harita göstergesi — pazar",
  pendingNote: "Bekleyen liste notu",
  best: "Çok satan rozeti",
  new: "Yeni rozeti",
  abs: "ABS gövde adı",
  pp: "Polipropilen gövde adı",
  colorsLabel: "Renk sayısı etiketi",
  sizesLabel: "Boy etiketi",
  sizesValue: "Boy değerleri",
  kidsSize: "Çocuk boyu etiketi",
  materialLabel: "Gövde etiketi",
  catalogLabel: "Katalog bağlantısı",
  productCta: "Ürün butonu",
  quoteCta: "Teklif butonu",
  explore: "Keşfet bağlantısı",
  discoverBrand: "Marka keşfet bağlantısı",
  allProducts: "Tüm ürünler bağlantısı",
  categoriesTitle: "Kategoriler başlığı",
  stlBrandBadge: "STL markası rozeti",
  orContact: "Alternatif iletişim metni",
  scriptAccent: "El yazısı vurgu",
  tagline_: "Slogan",
  rights: "Telif satırı",
  kvkk: "KVKK bağlantısı",
  privacy: "Gizlilik bağlantısı",
  cookiePrefs: "Çerez tercihleri bağlantısı",
  accept: "Kabul düğmesi",
  reject: "Ret düğmesi",
  policy: "Politika bağlantı yazısı",
  brandsHeading: "Markalar başlığı",
  corporateHeading: "Kurumsal başlığı",
  contactHeading: "İletişim başlığı",
  phoneLabel: "Telefon etiketi",
  emailLabel: "E-posta etiketi",
  emailFieldLabel: "E-posta alanı etiketi",
  addressLabel: "Adres etiketi",
  hoursLabel: "Çalışma saatleri etiketi",
  formTitle: "Form başlığı",
  nameLabel: "Ad Soyad etiketi",
  companyLabel: "Firma etiketi",
  messageLabel: "Mesaj etiketi",
  kvkkText: "KVKK onay metni",
  kvkkLink: "KVKK bağlantı yazısı",
  submit: "Gönder butonu",
  submitNote: "Form altı not",
  mapTitle: "Harita başlığı",
  home: "Ana sayfaya dön",
  missionEyebrow: "Üst başlık",
  missionTitle: "Başlık",
  buildingAlt: "Bina görseli açıklaması",
  lineAlt: "Üretim bandı görseli açıklaması",
  facilityAlt: "Tesis görseli açıklaması",
  introEyebrow: "Üst başlık",
  introTitle: "Başlık",
  introText: "Metin",
  portfolioEyebrow: "Üst başlık",
  portfolioTitle: "Başlık",
  portfolioDescription: "Açıklama",
  partnersKicker: "Üst başlık",
  partnersTitle: "Başlık",
  partnersNote: "Açıklama",
  hotspotsEyebrow: "Üst başlık",
  hotspotsTitle: "Başlık",
  hotspotsHint: "İpucu",
  rangeEyebrow: "Üst başlık",
  rangeTitle: "Başlık",
  rangeDescription: "Açıklama",
  categoriesLabel: "Kategori barı etiketi",
  vitrineTitle: "Vitrin başlığı",
  siteTitle: "Site adı",
};

/**
 * Dizi/nesne kapsayıcılarının tekil adı — "1. Adım", "2. Yorum" gibi
 * grup başlıkları buradan üretilir.
 */
export const GROUP_LABELS: Record<string, string> = {
  stats: "İstatistik",
  specBand: "Teknik satır",
  hotspots: "Nokta",
  steps: "Adım",
  posts: "Blog yazısı",
  slides: "Slayt",
  sizes: "Boy",
  items: "Öğe",
  range: "Ürün ailesi",
  paragraphs: "Paragraf",
  body: "Paragraf",
  alts: "Görsel açıklaması",
  barLinks: "Bar bağlantısı",
  valueProps: "Değer",
  specs: "Teknik değer",
  badges: "Rozetler",
  material: "Gövde adları",
  set: "Üçlü set",
  about: "Hakkında",
  brandAbout: "Marka anlatısı",
  spotlight: "Öne çıkan model",
  editorial: "Editoryal blok",
  quote: "Alıntı",
  hero: "Giriş",
  editorialHero: "Giriş",
  guide: "Boy rehberi",
  series: "Seri rehberi",
  shells: "Gövde bölümü",
  stages: "Üretim aşamaları",
  parts: "Parça bölümü",
  routine: "Rutin",
  bestSellers: "Çok satanlar",
  blog: "Blog bölümü",
  gallery: "Galeri",
  categoryCircles: "Kategori daireleri",
  reviews: "Yorumlar bölümü",
  cube: "Marka küpü",
  exportMap: "İhracat haritası",
  whoWeAre: "Biz kimiz",
  mission: "Misyon",
  vision: "Vizyon",
  contact: "İletişim",
  footer: "Alt bilgi",
  nav: "Menü",
  meta: "Arama motoru bilgisi",
  notFound: "404 sayfası",
  cookies: "Çerez bandı",
  brandPage: "Ortak marka metinleri",
};

/** Bu anahtarlar her zaman çok satırlı kutu ister */
export const MULTILINE_KEYS = new Set([
  "text",
  "body",
  "desc",
  "description",
  "lead",
  "excerpt",
  "sub",
  "note",
  "submitNote",
  "kvkkText",
  "pendingNote",
]);

export const fieldLabel = (key: string): string => FIELD_LABELS[key] ?? key;
export const groupLabel = (key: string): string => GROUP_LABELS[key] ?? FIELD_LABELS[key] ?? key;
